image:
  - Visual Studio 2017

build_script:
  - msbuild vector_n/vector_n.sln /p:Configuration=Debug /p:Platform="x86"
  - msbuild vector_n/vector_n.sln /p:Configuration=Release /p:Platform="x86"
  - msbuild vector_n/vector_n.sln /p:Configuration=Debug /p:Platform="x64"
  - msbuild vector_n/vector_n.sln /p:Configuration=Release /p:Platform="x64"

test_script:
  - cmd: call "vector_n/bin/x86_Debug/vector_n.exe"
  - cmd: call "vector_n/bin/x86_Release/vector_n.exe"
  - cmd: call "vector_n/bin/x64_Debug/vector_n.exe"
  - cmd: call "vector_n/bin/x64_Release/vector_n.exe"